-- Run this file in Supabase Dashboard → SQL Editor → New query.
-- The application accesses this database only from server-side API routes.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  auth_user_id uuid unique references auth.users(id) on delete cascade,
  name text not null,
  role text not null check (role in ('patient', 'doctor')),
  password_hash text not null
);

-- Needed when upgrading a schema created before Supabase Auth was enabled.
alter table public.users add column if not exists auth_user_id uuid unique references auth.users(id) on delete cascade;

create table if not exists public.patients (
  id bigint generated by default as identity primary key,
  user_id bigint not null unique references public.users(id) on delete cascade,
  doctor_id bigint not null references public.users(id) on delete restrict,
  condition text not null,
  start_date date not null
);

create table if not exists public.check_ins (
  id bigint generated by default as identity primary key,
  patient_id bigint not null references public.patients(id) on delete cascade,
  date date not null,
  pain numeric not null,
  swelling text not null check (swelling in ('none', 'mild', 'severe')),
  mobility numeric not null,
  fatigue numeric not null,
  sleep_quality numeric not null,
  exercises_completed integer not null default 0,
  created_at timestamptz not null default now(),
  unique(patient_id, date)
);

create table if not exists public.exercise_sessions (
  id bigint generated by default as identity primary key,
  patient_id bigint not null references public.patients(id) on delete cascade,
  exercise_type text not null,
  reps integer not null,
  average_angle numeric not null,
  range_of_motion numeric not null,
  form_score numeric not null,
  duration numeric not null,
  created_at timestamptz not null default now()
);

create table if not exists public.alerts (
  id bigint generated by default as identity primary key,
  patient_id bigint not null references public.patients(id) on delete cascade,
  type text not null,
  message text not null,
  severity text not null check (severity in ('low', 'medium', 'high')),
  acknowledged integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.gemini_analyses (
  id bigint generated by default as identity primary key,
  patient_id bigint not null references public.patients(id) on delete cascade,
  summary text not null,
  positive_trends jsonb not null default '[]'::jsonb,
  concerning_changes jsonb not null default '[]'::jsonb,
  adherence_summary text not null,
  clinician_points jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.gamification (
  patient_id bigint primary key references public.patients(id) on delete cascade,
  recovery_streak integer not null default 0,
  exercise_streak integer not null default 0,
  weekly_goal integer not null default 5,
  weekly_completed integer not null default 0
);

create index if not exists check_ins_patient_date_idx on public.check_ins(patient_id, date desc);
create index if not exists exercise_sessions_patient_created_idx on public.exercise_sessions(patient_id, created_at desc);
create index if not exists alerts_patient_created_idx on public.alerts(patient_id, created_at desc);

-- Enable RLS so data is never accidentally exposed through the public API.
-- Server requests use the secret key and bypass RLS; do not expose that key.
alter table public.users enable row level security;
alter table public.patients enable row level security;
alter table public.check_ins enable row level security;
alter table public.exercise_sessions enable row level security;
alter table public.alerts enable row level security;
alter table public.gemini_analyses enable row level security;
alter table public.gamification enable row level security;
